"""add clinical facts, reports, password, reference case, uploader

Revision ID: b635c9c40a67
Revises: 4a5df85f196f
Create Date: 2026-10-05 05:22:36.688722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b635c9c40a67'
down_revision: Union[str, Sequence[str], None] = '4a5df85f196f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_facts',
    sa.Column('id', sa.String(length=64), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('fact_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('ontology_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('superseded_by_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_clinical_facts_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['clinical_facts.id'], name=op.f('fk_clinical_facts_superseded_by_id_clinical_facts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_facts'))
    )
    op.create_index(op.f('ix_clinical_facts_conversation_id'), 'clinical_facts', ['conversation_id'], unique=False)
    op.create_table('pre_consultation_reports',
    sa.Column('id', sa.String(length=64), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consultation_session_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('hypotheses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultation_session_id'], ['consultation_sessions.id'], name=op.f('fk_pre_consultation_reports_consultation_session_id_consultation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pre_consultation_reports')),
    sa.UniqueConstraint('consultation_session_id', name=op.f('uq_pre_consultation_reports_consultation_session_id'))
    )
    op.create_table('clinical_fact_sources',
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['clinical_facts.id'], name=op.f('fk_clinical_fact_sources_fact_id_clinical_facts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_clinical_fact_sources_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id', 'message_id', name=op.f('pk_clinical_fact_sources'))
    )
    op.create_table('pre_consultation_report_facts',
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['clinical_facts.id'], name=op.f('fk_pre_consultation_report_facts_fact_id_clinical_facts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['pre_consultation_reports.id'], name=op.f('fk_pre_consultation_report_facts_report_id_pre_consultation_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'fact_id', name=op.f('pk_pre_consultation_report_facts'))
    )
    op.add_column('documents', sa.Column('uploaded_by_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(op.f('fk_documents_uploaded_by_id_users'), 'documents', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('medical_records', sa.Column('is_reference_case', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('medical_records', 'is_reference_case')
    op.drop_constraint(op.f('fk_documents_uploaded_by_id_users'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'uploaded_by_id')
    op.drop_table('pre_consultation_report_facts')
    op.drop_table('clinical_fact_sources')
    op.drop_table('pre_consultation_reports')
    op.drop_index(op.f('ix_clinical_facts_conversation_id'), table_name='clinical_facts')
    op.drop_table('clinical_facts')
    # ### end Alembic commands ###
