"""add consultation and report tables

Revision ID: 2c08aabe8267
Revises: 6e7b779ba7c1
Create Date: 2026-10-07 20:41:39.949844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c08aabe8267'
down_revision: Union[str, Sequence[str], None] = '6e7b779ba7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('doctor_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_consultation_sessions_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_sessions'))
    )
    op.create_index(op.f('ix_consultation_sessions_conversation_id'), 'consultation_sessions', ['conversation_id'], unique=False)
    op.create_table('clinical_facts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('consultation_session_id', sa.String(length=64), nullable=False),
    sa.Column('template_label', sa.String(length=255), nullable=False),
    sa.Column('fact_type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultation_session_id'], ['consultation_sessions.id'], name=op.f('fk_clinical_facts_consultation_session_id_consultation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_facts'))
    )
    op.create_index(op.f('ix_clinical_facts_consultation_session_id'), 'clinical_facts', ['consultation_session_id'], unique=False)
    op.create_table('pre_consultation_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('consultation_session_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultation_session_id'], ['consultation_sessions.id'], name=op.f('fk_pre_consultation_reports_consultation_session_id_consultation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pre_consultation_reports'))
    )
    op.create_index(op.f('ix_pre_consultation_reports_consultation_session_id'), 'pre_consultation_reports', ['consultation_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_consultation_reports_consultation_session_id'), table_name='pre_consultation_reports')
    op.drop_table('pre_consultation_reports')
    op.drop_index(op.f('ix_clinical_facts_consultation_session_id'), table_name='clinical_facts')
    op.drop_table('clinical_facts')
    op.drop_index(op.f('ix_consultation_sessions_conversation_id'), table_name='consultation_sessions')
    op.drop_table('consultation_sessions')
    # ### end Alembic commands ###
