"""add medical records and patient images

Revision ID: 4a5df85f196f
Revises: 8b2d3e4f5a61
Create Date: 2026-10-05 05:13:12.420067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5df85f196f'
down_revision: Union[str, Sequence[str], None] = '8b2d3e4f5a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.String(length=64), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_profile_id', sa.String(length=64), nullable=False),
    sa.Column('doctor_id', sa.String(length=64), nullable=True),
    sa.Column('consultation_session_id', sa.String(length=64), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultation_session_id'], ['consultation_sessions.id'], name=op.f('fk_medical_records_consultation_session_id_consultation_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], name=op.f('fk_medical_records_doctor_id_doctors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], name=op.f('fk_medical_records_patient_profile_id_patient_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_records'))
    )
    op.create_index(op.f('ix_medical_records_patient_profile_id'), 'medical_records', ['patient_profile_id'], unique=False)
    op.create_table('patient_images',
    sa.Column('id', sa.String(length=64), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medical_record_id', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('body_site', sa.String(length=128), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('confirmed_label', sa.String(length=128), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_patient_images_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], name=op.f('fk_patient_images_medical_record_id_medical_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_images'))
    )
    op.create_index(op.f('ix_patient_images_medical_record_id'), 'patient_images', ['medical_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_images_medical_record_id'), table_name='patient_images')
    op.drop_table('patient_images')
    op.drop_index(op.f('ix_medical_records_patient_profile_id'), table_name='medical_records')
    op.drop_table('medical_records')
    # ### end Alembic commands ###
