"""document uploader must be doctor

Revision ID: 83942f933af4
Revises: b635c9c40a67
Create Date: 2026-10-05 05:24:55.409246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83942f933af4'
down_revision: Union[str, Sequence[str], None] = 'b635c9c40a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_uploaded_by_id_users'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_uploaded_by_id_doctors'), 'documents', 'doctors', ['uploaded_by_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_uploaded_by_id_doctors'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_uploaded_by_id_users'), 'documents', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
